name: 'EC-validator'
description: To run ec against a particular container image built by RHTAP

inputs:
  image:
    description: The image reference
    required: true

  key:
    description: The public key for verifying signatures
    required: false

  policy:
    description: A policy configuration file which determines what policies are to be applied
    required: false

  identity:
    description: A regexp string used to match the certificate identity associated with the image
    required: false

  issuer:
    description: The OIDC issuer for validation
    required: false

  extra-params:
    description: This is to add some extra arguments into ec.
    required: false

runs:
  using: composite

  steps:
    - name: Run EC Validate
      uses: docker://quay.io/hacbs-contract/ec-cli:snapshot
      with:
        args: >
          validate image
          --policy "${{ inputs.policy }}"
          --image "${{ inputs.image }}"
          --public-key "${{ inputs.key }}"
          --certificate-identity-regexp="${{ inputs.identity }}"
          --certificate-oidc-issuer="${{ inputs.issuer }}"
          ${{ inputs.extra-params }}
          --output yaml
